/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocalTime } from './localTime';
import { UserInfo } from './userInfo';


export interface TransactionInfo { 
    id?: number;
    transactionDate?: string;
    transactionTime?: LocalTime;
    code?: string;
    debitCredit?: string;
    channel?: string;
    balance?: number;
    remark?: string;
    user?: UserInfo;
}

