/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserInfo { 
    id?: number;
    thaiName?: string;
    engName?: string;
    email?: string;
    pin?: string;
    role?: UserInfo.RoleEnum;
    account?: string;
    userId?: string;
    password?: string;
    updateDate?: string;
    updateBy?: string;
    createDate?: string;
    createBy?: string;
    status?: UserInfo.StatusEnum;
}
export namespace UserInfo {
    export type RoleEnum = 'PERSON' | 'CUSTOMER' | 'TALLER';
    export const RoleEnum = {
        Person: 'PERSON' as RoleEnum,
        Customer: 'CUSTOMER' as RoleEnum,
        Taller: 'TALLER' as RoleEnum
    };
    export type StatusEnum = 'PENDING_APPROVE' | 'APPROVED' | 'REJECTED' | 'DELETED';
    export const StatusEnum = {
        PendingApprove: 'PENDING_APPROVE' as StatusEnum,
        Approved: 'APPROVED' as StatusEnum,
        Rejected: 'REJECTED' as StatusEnum,
        Deleted: 'DELETED' as StatusEnum
    };
}


